# Generated by Django 5.0.1 on 2024-02-21 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.IntegerField()),
                ('type_of_property', models.CharField(max_length=100)),
                ('type_of_sale', models.CharField(max_length=100)),
                ('kitchen', models.CharField(max_length=100)),
                ('state_of_building', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('surface_of_good', models.FloatField()),
                ('number_of_facades', models.IntegerField()),
                ('living_area', models.FloatField()),
                ('garden_area', models.FloatField()),
                ('estimation', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
